### PR TITLE
Proposed release 1.1.2

### PR DESCRIPTION
**Pull request by jmrohwer**
I've fixed some bugs so it is time for a new release. In addition I've been working on getting the build to work on Python 3.12. This was a pain on windows, but all sorted now (numpy/numpy#25000, numpy/numpy#25073, https://github.com/numpy/numpy/pull/25160). It will have to wait for Numpy 2.0.0 though unless the changes are backported. The following can serve as a release announcement (edits welcome).

(The CI files are not at their final versions yet, that will have to wait until the PRs are available in numpy. I'd appreciate a review of the other commits).

# PySCeS Version 1.1.2

We are pleased to announce the release of the Python Simulator for Cellular Systems: PySCeS (https://pysces.github.io/) version 1.1.2. This is the second bugfix release in the 1.1 series.

## New features 

- Updated the build  for Python 3.12 (no more `distutils`).

## Bug fixes

- Fixed a bug with assignment rule evaluation when one species was an exact substring of another species.
- Removed a bunch of deprecated `scipy.*` functions that have moved to the `numpy.*` namespace.
- Cleaned up unused imports.

README: https://github.com/PySCeS/pysces/blob/master/README.md

DOCUMENTATION: https://pyscesdocs.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by jmrohwer** [comment]
FYI,  CI build problems have been sorted out: https://github.com/PySCeS/pysces/actions/runs/6930280357

Ultimately the `f2py` fixes should be backported to numpy 1.26 but until such time the Windows build needs to be run against numpy dev nightly builds.

@bgoli Would be appreciated if you could download the wheel and install in a new virtual environment under Python 3.12 to test :smiley: The tests are passing on CI, so should be good.

**Comment by bgoli** [comment]
Thanks, looking forward to testing! Aim is to have review done this week.

**Comment by bgoli** [comment]
I've been a bit delayed with the review, will be done this week.

**Review by bgoli — COMMENTED** [review]
Code changes reviewed, looks good to go, will continue with build/install tests etc

**Comment by jmrohwer** [comment]
@bgoli Thanks for the review. :+1: 
Don't spend too much time on testing builds and installs. I have refactored the build system to use `mesonpy` for a variety of reasons, which I will explain later. Am almost done, just need to run a couple of final tests. It is in the `mesonbuild` branch if you want to take a look. Will give you a heads up once I'm done.

**Review by bgoli — APPROVED** [review]
Installed and tested CI built Windows wheels for Python 3.10 and 3.12 into an environment with only pip preinstalled. Both installed, tests passed.

Awesome, 1.1.2 looks good to go!

**Pull request merged**
