### PR TITLE
Bug fix release

### PR DESCRIPTION
**Pull request by jmrohwer**
I've fixed some bugs, nothing major but for some projects I need a release with these fixes. Okay if I merge this and release 1.0.1?

### CODE REVIEW

**Review by bgoli — COMMENTED** [review]
Is it possible to leave 3.6 support in (there may be users using older Linux versions) or does it break the build process? If it does, please ignore.

**Comment by jmrohwer** [comment]
Okay I can put it back for the wheels. For Anaconda, it was out for 1.0.0 already but there it's easier to upgrade the Python. I just think providing wheels for 5 Python versions and 3 platforms is really pushing it... :raised_eyebrow: 
But no harm done. Are you otherwise okay with the PR?

**Review by bgoli — COMMENTED** [review]
The historical reason for this is that core2 can be used independently from PySCeS but this is okay to change now. I don't really like setup.py automatically executing code, what about specifying the version as the first line in a text file (version.txt) and then reading that in as the version number instead. This could potentially be useful outside of Python as well.

**Comment by jmrohwer** [comment]
> This has to do with the version.py change [commit 01fc890](https://github.com/PySCeS/pysces/pull/73/commits/01fc890556f243ae1c82d94e3b12b5c1f5985c97)
> 
> The historical reason for this is that core2 can be used independently from PySCeS but this is okay to change now. I don't really like setup.py automatically executing code, what about specifying the version as the first line in a text file (version.txt) and then reading that in as the version number instead. This could potentially be useful outside of Python as well.

Fixed in 6eb7b19

**Comment by jmrohwer** [comment]
> Is it possible to leave 3.6 support in (there may be users using older Linux versions) or does it break the build process? If it does, please ignore.

Fixed in bc869b0

**Comment by jmrohwer** [comment]
> +1 (i just committed adding version.txt to manifest.in)

And I added version.txt to mydata_files in setup.py (otherwise it doesn't get installed)

**Comment by jmrohwer** [comment]
@bgoli are you okay with the other commits? They are really just bug fixes.

**Review by bgoli — APPROVED** [review]
Looks good to me thanks @jmrohwer 👍

**Pull request merged**
